152 bug no correct direct translation with relations in components
Fekide/strapi-plugin-translate pull request #167
Opened 2023-04-06 13:00 UTC by sargreal

When translating relations in a component, the relation is not translated and when clicking on the
relation field an error is thrown. The bug was that the relation parsing did not handle repeated
components correctly. Another connected issue was that after translating, all fields in the repeated
components were opening simultaneously, which was caused by a missing __temp_key__.

fix https://github.com/Fekide/strapi-plugin-translate/issues/152

2023-04-06 13:29 UTC, sargreal commented
Tests are probably failing because of the addition of the categories-page which makes the batch translation page load slower. Will look into that probably tomorrow

2023-04-06 15:48 UTC, layaxx requested changes
Functionality looks good. Tests passed with increased `defaultCommandTimeout`

2023-04-06 15:48 UTC, layaxx commented on playground/package.json
> -    "@strapi/plugin-graphql": "^4.7.1",
you should remove it from the template as well

2023-04-07 20:20 UTC, layaxx approved these changes

2023-04-09 21:12 UTC, merged